spring: 
  profiles:
  active:
  - dev

---
server:
  port: 8001

#mybatis
mybatis: 
  type-aliases-package: com.springcloud.entities  #实体类的所在的包
  mapper-locations: 
  - classpath:mapper/*.xml  #mapper映射文件

spring: 
  profiles: dev
  application: 
    name: microservicecloud-dept
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: 
    service-url:
      #defaultZone: http://localhost:7001/eureka #客户端注册金eureka服务
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #客户端注册进eureka服务
  instance: 
    instance-id: microservicecloud-dept8001 #自定义相关的服务名称信息
    prefer-ip-address: true #注册表中访问路径显示IP地址

#在eureka注册中心点击链接时跳转到新页面显示的服务信息
info: 
  app.name: microservicecloud
  build.artifactId: $project.microservicecloud$
  build.version: $project.version$

---
server:
  port: 8001

#mybatis
mybatis: 
  type-aliases-package: com.springcloud.entities  #实体类的所在的包
  mapper-locations: 
  - classpath:mapper/*.xml  #mapper映射文件

spring: 
  profiles: test
  application: 
    name: microservicecloud-dept
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: 
    service-url:
      #defaultZone: http://localhost:7001/eureka #客户端注册金eureka服务
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #客户端注册进eureka服务
  instance: 
    instance-id: microservicecloud-dept8001 #自定义相关的服务名称信息
    prefer-ip-address: true #注册表中访问路径显示IP地址

#在eureka注册中心点击链接时跳转到新页面显示的服务信息
info: 
  app.name: microservicecloud
  build.artifactId: $project.microservicecloud$
  build.version: $project.version$